TreeManager/Controllers/NodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using TreeManager.Database;
using TreeManager.Models;
using jsTree3.Models;

namespace TreeManager.Controllers
{
    [Authorize]
    public class NodesController : Controller
    {
        private readonly NodeRepository nodeRepository = new NodeRepository();

        // GET: Nodes
        public ActionResult Index()
        {
            List<JsTree3Node> jsTree3NodeManage = nodeRepository.ConvertModelToJS3Tree();
            ViewBag.DbCount = nodeRepository.FindAll().ToList().Count;
            if (jsTree3NodeManage.Count > 0)
                return View(jsTree3NodeManage[0]);
            else
                return View(new JsTree3Node());
        }

        public ActionResult Table(string searchString)
        {
            if (!String.IsNullOrEmpty(searchString))
            {
                return View(nodeRepository.Search(searchString));
            }
            else
            {
                return View(nodeRepository.FindAll());
            }
        }

        // GET: Nodes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Node node = nodeRepository.FindById(Convert.ToInt32(id));
            if (node == null)
            {
                return HttpNotFound();
            }
            return View(node);
        }

        // GET: Nodes/Create
        public ActionResult Create()
        {
            ViewBag.IdParent = new SelectList(nodeRepository.FindAll(), "Id", "Value");
            return View();
        }

        // POST: Nodes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Value,IdParent")] Node node)
        {
            if (ModelState.IsValid)
            {
                nodeRepository.Add(node);
                return RedirectToAction("Index");
            }

            ViewBag.IdParent = new SelectList(nodeRepository.FindAll(), "Id", "Value", node.IdParent);
            return View(node);
        }

        // GET: Nodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Node node = nodeRepository.FindById(Convert.ToInt32(id));
            if (node == null)
            {
                return HttpNotFound();
            }
            if (node.IdParent == null)
                ViewBag.IdParent = new SelectList(new List<int>());
            else
            {
                List<Node> nodes = nodeRepository.FindAll().ToList();
                nodes.Remove(node);
                ViewBag.IdParent = new SelectList(nodes, "Id", "Value", node.IdParent);
            }
            return View(node);
        }

        // POST: Nodes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Value,IdParent")] Node node)
        {
            Node oldNode = nodeRepository.FindById(node.Id);
            if (oldNode.IdParent == null && node.IdParent != null)
                node.IdParent = null;
            if (node.IdParent == node.Id)
                node.IdParent = oldNode.IdParent;

            if (ModelState.IsValid)
            {
                nodeRepository.Update(node);
                return RedirectToAction("Index");
            }
            ViewBag.IdParent = new SelectList(nodeRepository.FindAll(), "Id", "Value", node.IdParent);
            return View(node);
        }

        // GET: Nodes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Node node = nodeRepository.FindById(Convert.ToInt32(id));
            if (node == null)
            {
                return HttpNotFound();
            }
            return View(node);
        }

        // POST: Nodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            nodeRepository.CascadeDeleteById(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                nodeRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TreeManager/Views/Nodes/Create.cshtml
@model TreeManager.Models.Node

@{
    ViewBag.Title = "Dodaj nowy węzeł";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, "Nazwa rodzica", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdParent", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdParent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do drzewa", "Index") |
    @Html.ActionLink("Wróć do listy", "Table")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TreeManager/Views/Nodes/Delete.cshtml
@model TreeManager.Models.Node

@{
    ViewBag.Title = "Usuń";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>Czy na pewno chcesz usunąć poniższy węzeł?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdParent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdParent)
        </dd>
    </dl>

    <div>
        @if (Model.ChildNodes.Count > 0)
        {
            @Html.Raw("<p><b>Uwaga:</b> usunięcie tego węzła spowoduje usunięcie wszystkich jego węzłów-dzieci</p>");
        }
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" /> <br />
            @Html.ActionLink("Wróć do drzewa", "Index") |
            @Html.ActionLink("Wróć do listy", "Table")
        </div>
    }
</div>

TreeManager/Views/Nodes/Details.cshtml
@model TreeManager.Models.Node

@{
    ViewBag.Title = "Szczegóły";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Węzeł</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdParent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdParent)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Wróć do drzewa", "Index") | 
    @Html.ActionLink("Wróć do listy", "Table") <br />
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Usuń", "Delete", new { id = Model.Id })
</p>

TreeManager/Views/Nodes/Edit.cshtml
@model TreeManager.Models.Node

@{
    ViewBag.Title = "Edytuj";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Węzeł</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.IdParent, "Nazwa rodzica", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdParent", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdParent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć do drzewa", "Index") | 
    @Html.ActionLink("Wróć do listy", "Table")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TreeManager/Views/Nodes/Index.cshtml
@model jsTree3.Models.JsTree3Node

@{
    ViewBag.Title = "Drzewo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@Styles.Render("~/Content/jstree")

<p>
    @Html.ActionLink("Dodaj nowy węzeł", "Create") <br />
    @Html.ActionLink("Tabela wszystkich węzłów", "Table")
</p>
<p>Wskazówka: Wciśnij dwukrotnie na węzeł, aby zobaczyć jego szczegółowe dane</p>

<div id="treeManage"></div>
@Scripts.Render("~/bundles/jstree")

<!--/Views/Nodes/Index-->
<script>
    $.jstree.defaults.core.themes.variant = "large";
    $('#treeManage').jstree({
        'core': {
            'check_callback': CheckOperation(),
            'data':@Html.Raw(Json.Encode(Model)),
        },
        'plugins': ['dnd']
    }).bind("move_node.jstree", function (e, data) {
        var movedNodeId = data.node.id;
        var newParentId = data.parent;
    });

    function CheckOperation(operation, node, parent, position, more) {
        if (operation == "move_node") {
            return true;
        }
        else if (operation == "create_node") {
            return false;
        }
        else if (operation == "rename_node") {
            return false;
        }
        else if (operation == "delete_node") {
            return false;
        }
        else if (operation == "copy_node") {
            return false;
        }
        else if (operation == "edit") {
            return false;
        }
        else
            return true;
    }

    $('#treeManage').bind("dblclick.jstree", ".jstree-anchor", $.proxy(function (e) {
        var node = $(e.target).closest("li");
        var id = node[0].id; //id of the selected node
        if (@ViewBag.DbCount > 0)
            window.open("./Nodes/Details/" + id, "_top");
    }));

</script>

TreeManager/Views/Nodes/Table.cshtml
@model IEnumerable<TreeManager.Models.Node>

@{
    ViewBag.Title = "Lista węzłów";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Dodaj nowy węzeł", "Create") <br />
    @Html.ActionLink("Wróć do drzewa", "Index")
</p>
<div>
    @using (Html.BeginForm("Table", "Nodes", FormMethod.Get))
    {
        <p>
            Nazwa: @Html.TextBox("SearchString") 
            <input type="submit" value="Szukaj" />
        </p>
    }
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdParent)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdParent)
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Szczegóły", "Details", new { id = item.Id }) |
                @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>